### ISSUE TITLE
Using HTML in message

### ISSUE THREAD

**Issue by RoyvanEmpel** [mickelsonmichael/js-snackbar#14]
Hello!

I was trying out the js-snackbar library and was wondering if it is possible to add the use of html tags in my message. So that way I could use something like **`PHP Error:`**` Biep boep something wrong`

Greetings, 
Roy

**Comment by RoyvanEmpel** [comment]
Ooh and I had a problem with the non minified versions on the js and css files. Js gave an error and the css was only half working.

**Comment by RoyvanEmpel** [comment]
Also the minified versions don't have the positioning

**Comment by gewy** [comment]
Hi,
I guess there is a reason why Michael use textContent instead of innerHTML.
Anyway if you want html content just do this in _Create function :
// _Message.textContent = _Options.message;
   _Message.innerHTML = _Options.message;

**Comment by mickelsonmichael** [comment]
> Ooh and I had a problem with the non minified versions on the js and css files. Js gave an error and the css was only half working.

> Also the minified versions don't have the positioning

Yes, my  apologies, I had a clean install of VS Code and forgot to include automatic minification, so those slipped my mind. Please try the new updated min files, they should have the updated position code now (and the error should be resolved)

**Comment by mickelsonmichael** [comment]
> I guess there is a reason why Michael use textContent instead of innerHTML.

I mainly wanted to maintain a consistent size/shape to the Snackbar, but if there's genuine interest then I can modify the code easily as you've pointed out

> Anyway if you want html content just do this in _Create function :
> // _Message.textContent = _Options.message;
> _Message.innerHTML = _Options.message;

**Comment by mickelsonmichael** [comment]
> I was trying out the js-snackbar library and was wondering if it is possible to add the use of html tags in my message. So that way I could use something like **`PHP Error:`**` Biep boep something wrong`

This has been added to the v1.2 release (you can pull that from the releases tab or from `master`)

**Comment by RoyvanEmpel** [comment]
Great! thanks you :)
