### ISSUE TITLE
setting timeout to 0 should be equivalent to false

### ISSUE THREAD

**Issue by gewy** [mickelsonmichael/js-snackbar#21]
Hi,
What could be the goal to display a notification with a timeout set to 0 as it will never be seen ?
As this value has no usability it could be equivalent to **no timeout**.
It will be easiest to use as we should have only one type of parameter to process.
In my case I have to add a test to replace 0 by false.
Most Toast component that I know are using 0 to prevent auto hiding.
JY

**Comment by mickelsonmichael** [comment]
See Release v1.3 for a fixed version of this
