### ISSUE TITLE
setting status to null raise an exception

### ISSUE THREAD

**Issue by gewy** [mickelsonmichael/js-snackbar#22]
Hi,
If status is **null** => _Uncaught TypeError: Cannot read property 'toLowerCase' of null_
If status is **undefined** => no error.
You should replace 
`status: userOptions?.status !== undefined ? userOptions.status.toLowerCase().trim() : "",`
by
`status: userOptions?.status ? userOptions.status.toLowerCase().trim() : "",`
JY

**Comment by mickelsonmichael** [comment]
See Release v1.3 for a fix version
