### ISSUE TITLE
Dispose with JS

### ISSUE THREAD

**Issue by ahmadsamei** [mickelsonmichael/js-snackbar#75]
Hi
Does it have Dispose method for use in my function btn?

**Comment by mickelsonmichael** [comment]
Hi @ahmadsamei, I think you're looking for the `dismiss` property on an action.

```js
 var message = SnackBar({
  message: "Click the button!",
  timeout: 30000,
  actions: [
    {
      text: "I close and act!",
      dismiss: true, // will close the snackbar after the function completes
      function: function () {
        alert("You've done an action and closed.");
      }
    }
  ]
})
```

You can read more about it on the README
https://github.com/mickelsonmichael/js-snackbar#actions

**Comment by mickelsonmichael** [comment]
I'm going to close this issue now, hopefully I have pointed you in the correct direction. If you need more help feel free to reply here or create a new issue.
