### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by EmpireOfTheTsun** [mickelsonmichael/js-snackbar#76]
README states: "Simply call Snackbar()"
When it should be SnackBar().

Minor, but inexperienced users may struggle. A brief entry on how to install + an example would take this even further.

Thanks for an otherwise performant & easy to use library :)

**Comment by mickelsonmichael** [comment]
@EmpireOfTheTsun thanks so much for pointing that out, and I'm glad you're enjoying the library!
