### ISSUE TITLE
Unable to bind Snackbar to container when using query selector string

### ISSUE THREAD

**Issue by falxen** [mickelsonmichael/js-snackbar#83]
Hi Michael,

Great job on this plugin! Unfortunately I can't bind to a container when I specify a string to be used by the query selector. E.g. ".messages" or "#container" or even "body" gives the error below

```
js-snackbar.1.5.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'children')
    at getOrAddContainerIn (js-snackbar.1.5.min.js:2:146)
    at _setContainer (js-snackbar.1.5.min.js:2:13)
    at _create (js-snackbar.1.5.min.js:1:161)
    at SnackBar (js-snackbar.1.5.min.js:4:290)
```
However specifying `document.body` works fine. i.e.
```
SnackBar({
    message: "Hello world.",
    status: "info",
    position: "tm",
    timeout: false,
    width: "100vw",
    container: "body",
    fixed: true
});
```

Leaving out the **container** option entirely also works fine. Thanks!

**Comment by mickelsonmichael** [comment]
Hi @falxen sorry for the delayed response to this! I've fixed the issue, can you please verify it works for you with the latest version?

**Comment by mickelsonmichael** [comment]
Feel free to re-open if your issue persists, but I'm closing for now
