### ISSUE TITLE
Option to change positioning and add icon

### ISSUE THREAD

**Issue by UmarEjaz** [mickelsonmichael/js-snackbar#9]
Kindly provide option to change positioning and add icon. If the position is top right corner then toasts should be stacked vertically downward and the latest toast should be at the top.

**Comment by mickelsonmichael** [comment]
@UmarEjaz I have added the ability to choose between the corners. However, to keep with the style of the Snackbars I chose to display the latest message on the bottom of the stack. I hope that isn't an issue

For your second request, adding an icon, did you have an icon library in mind? Or did you have a certain icon you were hoping for? I could use some more details

**Comment by UmarEjaz** [comment]
> @UmarEjaz I have added the ability to choose between the corners. However, to keep with the style of the Snackbars. I chose to display the latest message on the bottom of the stack. I hope that isn't an issue. You can try it out via the new "Positioning" section at https://www.michaelmickelson.com/js-snackbar#Positioning
> 
> For your second request, adding an icon, did you have an icon library in mind? Or did you have a certain icon you were hoping for? I could use some more details

@mickelsonmichael So nice of you. I was thinking of simple icons like a "tick" for success, any error icon for error and similarly icons for info and warning. However, if cdn of font-awesome can be linked and we can add icons from there, that would be nice too.

**Comment by gewy** [comment]
Hi,
_This is missing when getPositionClass is called.

**Comment by mickelsonmichael** [comment]
@UmarEjaz I have added the ability to define the message as HTML as part of #14 

This can be a temporary solution until I have some more time in my schedule to get to the actual solution of adding icons

**Comment by mickelsonmichael** [comment]
> Hi,
> _This is missing when getPositionClass is called.

Check this against the latest v1.2 version, and if it still persists then please create a new Issue

**Comment by mickelsonmichael** [comment]
@UmarEjaz I've added some basic icon functionality that should serve some basic purposes
